library(XML)
library(jsonlite)
library(data.table)
library(RMySQL)
library(rhdf5)
library(httr)
library(swirl)
library(dplyr)
library(plyr)
library(Hmisc)
library(reshape2)
library(curl)
library(stringr)

DT_test <- read.table("./UCI HAR Dataset/test/X_test.txt")
LB_test <- read.table("./UCI HAR Dataset/test/y_test.txt")
SB_test <- read.table("./UCI HAR Dataset/test/subject_test.txt")
DT_feature <- read.table("./UCI HAR Dataset/features.txt")
DT_train <- read.table("./UCI HAR Dataset/train/X_train.txt")
LB_train <- read.table("./UCI HAR Dataset/train/y_train.txt")
SB_train <- read.table("./UCI HAR Dataset/train/subject_train.txt")
Act_LB <- read.table("./UCI HAR Dataset/activity_labels.txt")


DT_test <- DT_test %>% mutate(activity_label = Act_LB[LB_test$V1,"V2"],subject = c(SB_test$V1))
DT_train <- DT_train %>% mutate(activity_label = Act_LB[LB_train$V1,"V2"],subject = c(SB_train$V1))
DT_merge <- rbind(DT_test,DT_train)
DT_merge <- setnames(DT_merge,grep("^V",names(DT_merge)),as.character(DT_feature$V2))
DT_merge_mean_std <- DT_merge[,c(grep("*[mM][eE][aA][nN]*|*[sS][tT][dD]*",DT_feature$V2,value=TRUE),"activity_label","subject")]
DT_new <- as.data.table(DT_merge_mean_std %>% group_by(activity_label,subject) %>% summarise_each(funs(mean)))
write.table(DT_new,"./UCI_HAR_Dataset.txt",row.names = FALSE)
